baseURL = "/"
languageCode = "en-us"
title = "Simon Lindgren"
theme = "orbit"

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Stefanie Möllberg"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-custom.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Stefanie Möllberg"
        tagline = "Data Analyst | Project Manager | Engineer"
        avatar = "profile.jpeg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: stefaniemollberg@gmail.com"
        title = "stefaniemollberg@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+46735321941"
        title = "+4673 532 19 41"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/stefaniemollberg"
        title = "linkedin.com/in/stefaniemollberg"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Strategic Management and Control"
        college = "University of Linköping"
        dates = "2011 - 2016"

        [[params.education.list]]
        degree = "Business and Mechanical Engineering"
        college = "Technische Universität Graz"
        dates = "2013 - 2014"

        [[params.education.list]]
        degree = "BSc in Mechanical Engineering"
        college = "University of Linköping"
        dates = "2011 - 2013"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Swedish"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Fluent"

        [[params.language.list]]
        language = "German"
        level = "Proficent"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Adventures!"

	      [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Skiing"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Data Analyst | Project Manager | Engineer** Passionate about data driven Insight and Business Transformation"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Analyst"
        dates = "Aug 2016 - Present"
        company = "Nepa AB"

        [[params.jobs.list]]
        position = "Master Thesis Research "
        dates = "Feb 2016 - Jun 2018"
        company = "Sectra"
        details = "Thesis investigating the customer perceived value of IT-security and how this value can be visualised."

        [[params.jobs.list]]
        position = "Market Research Analyst"
        dates = "Oct 2015 - Feb 2016"
        company = "Sectra"
        details = "Part time work during the last years of school. Assisted the sales team at Sectra Communications by collecting data and mapping potential new customers."

        [[params.jobs.list]]
        position = "Marketing Assistant"
        dates = "Jun 2013 - Aug 2013"
        company = "Svenska Bostadsfonden"
        details = "Informed potential investors about the investment fund, mostly through telephone. An experience with emphasis on performance and results."

    # Projects section

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "R"
        level = "90%"

	[[params.skills.list]]
        skill = "Market Research"
        level = "90%"

	[[params.skills.list]]
        skill = "Marketing mixed modeling"
        level = "80%"

        [[params.skills.list]]
        skill = "Data Science"
        level = "80%"

        [[params.skills.list]]
        skill = "Statistics"
        level = "75%"

	[[params.skills.list]]
        skill = "Project Management"
        level = "80%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
